export default [
  'Brasil',
  'Afeganistão',
  'África do Sul',
  'Albânia',
  'Alemanha',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antártida',
  'Antígua e Barbuda',
  'Arábia Saudita',
  'Argélia',
  'Argentina',
  'Armênia',
  'Aruba',
  'Austrália',
  'Áustria',
  'Azerbaijão',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Bélgica',
  'Belize',
  'Benin',
  'Bermudas',
  'Bielorrússia',
  'Bolívia',
  'Bósnia e Herzegovina',
  'Botsuana',
  'Brunei',
  'Bulgária',
  'Burkina Faso',
  'Burundi',
  'Butão',
  'Cabo Verde',
  'Camarões',
  'Camboja',
  'Canadá',
  'Caribe Holandês',
  'Catar',
  'Cazaquistão',
  'Chade',
  'Chéquia',
  'Chile',
  'China',
  'Chipre',
  'Cidade do Vaticano',
  'Colômbia',
  'Comores',
  'Congo - Brazzaville',
  'Congo - Kinshasa',
  'Coreia do Norte',
  'Coreia do Sul',
  'Costa do Marfim',
  'Costa Rica',
  'Croácia',
  'Cuba',
  'Curaçao',
  'Dinamarca',
  'Djibuti',
  'Dominica',
  'Egito',
  'El Salvador',
  'Emirados Árabes Unidos',
  'Equador',
  'Eritreia',
  'Eslováquia',
  'Eslovênia',
  'Espanha',
  'Essuatíni',
  'Estados Unidos',
  'Estônia',
  'Etiópia',
  'Fiji',
  'Filipinas',
  'Finlândia',
  'França',
  'Gabão',
  'Gâmbia',
  'Gana',
  'Geórgia',
  'Geórgia do Sul e Ilhas Sandwich do Sul',
  'Gibraltar',
  'Granada',
  'Grécia',
  'Groenlândia',
  'Guadalupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guiana',
  'Guiana Francesa',
  'Guiné',
  'Guiné Equatorial',
  'Guiné-Bissau',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungria',
  'Iémen',
  'Ilha Bouvet',
  'Ilha Christmas',
  'Ilha de Man',
  'Ilha Norfolk',
  'Ilhas Aland',
  'Ilhas Cayman',
  'Ilhas Cocos (Keeling)',
  'Ilhas Cook',
  'Ilhas Falkland (Malvinas)',
  'Ilhas Faroe',
  'Ilhas Heard e McDonald',
  'Ilhas Marianas do Norte',
  'Ilhas Marshall',
  'Ilhas Pitcairn',
  'Ilhas Salomão',
  'Ilhas Turks e Caicos',
  'Ilhas Ultramarinas Menores dos EUA',
  'Ilhas Virgens Americanas',
  'Ilhas Virgens Britânicas',
  'Índia',
  'Indonésia',
  'Irã',
  'Iraque',
  'Irlanda',
  'Islândia',
  'Israel',
  'Itália',
  'Jamaica',
  'Japão',
  'Jersey',
  'Jordânia',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letônia',
  'Líbano',
  'Libéria',
  'Líbia',
  'Liechtenstein',
  'Lituânia',
  'Luxemburgo',
  'Macau',
  'Macedônia do Norte',
  'Madagascar',
  'Malásia',
  'Malawi',
  'Maldivas',
  'Mali',
  'Malta',
  'Marrocos',
  'Martinica',
  'Maurício',
  'Mauritânia',
  'Mayotte',
  'México',
  'Mianmar (Birmânia)',
  'Micronésia',
  'Moçambique',
  'Moldávia',
  'Mônaco',
  'Mongólia',
  'Montenegro',
  'Montserrat',
  'Namíbia',
  'Nauru',
  'Nepal',
  'Nicarágua',
  'Níger',
  'Nigéria',
  'Niue',
  'Noruega',
  'Nova Caledônia',
  'Nova Zelândia',
  'Omã',
  'Países Baixos',
  'Palau',
  'Palestina',
  'Panamá',
  'Papua Nova Guiné',
  'Paquistão',
  'Paraguai',
  'Peru',
  'Polinésia Francesa',
  'Polônia',
  'Porto Rico',
  'Portugal',
  'Quênia',
  'Quirguistão',
  'Reino Unido',
  'República Centro-Africana',
  'República Dominicana',
  'Reunião',
  'Romênia',
  'Ruanda',
  'Rússia',
  'Saara Ocidental',
  'Samoa',
  'Samoa Americana',
  'San Marino',
  'Santa Helena',
  'Santa Lúcia',
  'São Bartolomeu',
  'São Cristóvão e Nevis',
  'São Martinho',
  'São Pedro e Miquelon',
  'São Tomé e Príncipe',
  'São Vicente e Granadinas',
  'Senegal',
  'Serra Leoa',
  'Sérvia',
  'Sérvia',
  'Seychelles',
  'Singapura',
  'Sint Maarten',
  'Síria',
  'Somália',
  'Sri Lanka',
  'Sudão',
  'Sudão do Sul',
  'Suécia',
  'Suíça',
  'Suriname',
  'Svalbard e Jan Mayen',
  'Tailândia',
  'Taiwan',
  'Tajiquistão',
  'Tanzânia',
  'Território Britânico do Oceano Índico',
  'Territórios Franceses do Sul',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trindade e Tobago',
  'Tunísia',
  'Turcomenistão',
  'Turquia',
  'Tuvalu',
  'Ucrânia',
  'Uganda',
  'Uruguai',
  'Uzbequistão',
  'Vanuatu',
  'Venezuela',
  'Vietnã',
  'Wallis e Futuna',
  'Zâmbia',
  'Zimbábue',
];